name: force_inject
description: A zero-dependency DI container for Dart, inspired by .NET Core. This is the Way.
version: 0.2.1
repository: https://github.com/diegomgarcia/forceinject
homepage: https://github.com/diegomgarcia/forceinject

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: any

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:

dev_dependencies:
  test: ^1.24.0
